#pragma once

namespace uwm
{
	static constexpr uint32_t refreshbk = WM_USER + 1;
	static constexpr uint32_t invoke_timer = WM_USER + 2;
	static constexpr uint32_t unload = WM_USER + 3;
}

enum class CallbackID : uint32_t
{
	on_always_on_top_changed = WM_USER + 10,
	on_char,
	on_colours_changed,
	on_cursor_follow_playback_changed,
	on_download_file_done,
	on_drag_drop,
	on_drag_enter,
	on_drag_leave,
	on_drag_over,
	on_dsp_preset_changed,
	on_focus,
	on_font_changed,
	on_get_album_art_done,
	on_http_request_done,
	on_item_focus_change,
	on_item_played,
	on_key_down,
	on_key_up,
	on_library_items_added,
	on_library_items_changed,
	on_library_items_removed,
	on_load_image_done,
	on_locations_added,
	on_main_menu,
	on_metadb_changed,
	on_mouse_lbtn_dblclk,
	on_mouse_lbtn_down,
	on_mouse_lbtn_up,
	on_mouse_leave,
	on_mouse_mbtn_dblclk,
	on_mouse_mbtn_down,
	on_mouse_mbtn_up,
	on_mouse_move,
	on_mouse_rbtn_dblclk,
	on_mouse_rbtn_down,
	on_mouse_rbtn_up,
	on_mouse_wheel,
	on_mouse_wheel_h,
	on_notify_data,
	on_output_device_changed,
	on_paint,
	on_playback_dynamic_info,
	on_playback_dynamic_info_track,
	on_playback_edited,
	on_playback_follow_cursor_changed,
	on_playback_new_track,
	on_playback_order_changed,
	on_playback_pause,
	on_playback_queue_changed,
	on_playback_seek,
	on_playback_starting,
	on_playback_stop,
	on_playback_time,
	on_playlist_item_ensure_visible,
	on_playlist_items_added,
	on_playlist_items_removed,
	on_playlist_items_reordered,
	on_playlist_items_selection_change,
	on_playlist_stop_after_current_changed,
	on_playlist_switch,
	on_playlists_changed,
	on_replaygain_mode_changed,
	on_script_unload,
	on_selection_changed,
	on_size,
	on_volume_change,
};

static const std::map<const CallbackID, const std::wstring> g_callback_name_map =
{
	{ CallbackID::on_always_on_top_changed, L"on_always_on_top_changed" },
	{ CallbackID::on_char, L"on_char" },
	{ CallbackID::on_colours_changed, L"on_colours_changed" },
	{ CallbackID::on_cursor_follow_playback_changed, L"on_cursor_follow_playback_changed" },
	{ CallbackID::on_download_file_done, L"on_download_file_done" },
	{ CallbackID::on_drag_drop, L"on_drag_drop" },
	{ CallbackID::on_drag_enter, L"on_drag_enter" },
	{ CallbackID::on_drag_leave, L"on_drag_leave" },
	{ CallbackID::on_drag_over, L"on_drag_over" },
	{ CallbackID::on_dsp_preset_changed, L"on_dsp_preset_changed" },
	{ CallbackID::on_focus, L"on_focus" },
	{ CallbackID::on_font_changed, L"on_font_changed" },
	{ CallbackID::on_get_album_art_done, L"on_get_album_art_done" },
	{ CallbackID::on_http_request_done, L"on_http_request_done" },
	{ CallbackID::on_item_focus_change, L"on_item_focus_change" },
	{ CallbackID::on_item_played, L"on_item_played" },
	{ CallbackID::on_key_down, L"on_key_down" },
	{ CallbackID::on_key_up, L"on_key_up" },
	{ CallbackID::on_library_items_added, L"on_library_items_added" },
	{ CallbackID::on_library_items_changed, L"on_library_items_changed" },
	{ CallbackID::on_library_items_removed, L"on_library_items_removed" },
	{ CallbackID::on_load_image_done, L"on_load_image_done" },
	{ CallbackID::on_locations_added, L"on_locations_added" },
	{ CallbackID::on_main_menu, L"on_main_menu" },
	{ CallbackID::on_metadb_changed, L"on_metadb_changed" },
	{ CallbackID::on_mouse_lbtn_dblclk, L"on_mouse_lbtn_dblclk" },
	{ CallbackID::on_mouse_lbtn_down, L"on_mouse_lbtn_down" },
	{ CallbackID::on_mouse_lbtn_up, L"on_mouse_lbtn_up" },
	{ CallbackID::on_mouse_leave, L"on_mouse_leave" },
	{ CallbackID::on_mouse_mbtn_dblclk, L"on_mouse_mbtn_dblclk" },
	{ CallbackID::on_mouse_mbtn_down, L"on_mouse_mbtn_down" },
	{ CallbackID::on_mouse_mbtn_up, L"on_mouse_mbtn_up" },
	{ CallbackID::on_mouse_move, L"on_mouse_move" },
	{ CallbackID::on_mouse_rbtn_dblclk, L"on_mouse_rbtn_dblclk" },
	{ CallbackID::on_mouse_rbtn_down, L"on_mouse_rbtn_down" },
	{ CallbackID::on_mouse_rbtn_up, L"on_mouse_rbtn_up" },
	{ CallbackID::on_mouse_wheel, L"on_mouse_wheel" },
	{ CallbackID::on_mouse_wheel_h, L"on_mouse_wheel_h" },
	{ CallbackID::on_notify_data, L"on_notify_data" },
	{ CallbackID::on_output_device_changed, L"on_output_device_changed" },
	{ CallbackID::on_paint, L"on_paint" },
	{ CallbackID::on_playback_dynamic_info, L"on_playback_dynamic_info" },
	{ CallbackID::on_playback_dynamic_info_track, L"on_playback_dynamic_info_track" },
	{ CallbackID::on_playback_edited, L"on_playback_edited" },
	{ CallbackID::on_playback_follow_cursor_changed, L"on_playback_follow_cursor_changed" },
	{ CallbackID::on_playback_new_track, L"on_playback_new_track" },
	{ CallbackID::on_playback_order_changed, L"on_playback_order_changed" },
	{ CallbackID::on_playback_pause, L"on_playback_pause" },
	{ CallbackID::on_playback_queue_changed, L"on_playback_queue_changed" },
	{ CallbackID::on_playback_seek, L"on_playback_seek" },
	{ CallbackID::on_playback_starting, L"on_playback_starting" },
	{ CallbackID::on_playback_stop, L"on_playback_stop" },
	{ CallbackID::on_playback_time, L"on_playback_time" },
	{ CallbackID::on_playlist_item_ensure_visible, L"on_playlist_item_ensure_visible" },
	{ CallbackID::on_playlist_items_added, L"on_playlist_items_added" },
	{ CallbackID::on_playlist_items_removed, L"on_playlist_items_removed" },
	{ CallbackID::on_playlist_items_reordered, L"on_playlist_items_reordered" },
	{ CallbackID::on_playlist_items_selection_change, L"on_playlist_items_selection_change" },
	{ CallbackID::on_playlist_stop_after_current_changed, L"on_playlist_stop_after_current_changed" },
	{ CallbackID::on_playlist_switch, L"on_playlist_switch" },
	{ CallbackID::on_playlists_changed, L"on_playlists_changed" },
	{ CallbackID::on_replaygain_mode_changed, L"on_replaygain_mode_changed" },
	{ CallbackID::on_script_unload, L"on_script_unload" },
	{ CallbackID::on_selection_changed, L"on_selection_changed" },
	{ CallbackID::on_size, L"on_size" },
	{ CallbackID::on_volume_change, L"on_volume_change" },
};

static const std::map<const uint32_t, const CallbackID> g_msg_callback_map =
{
	{ WM_LBUTTONDOWN, CallbackID::on_mouse_lbtn_down },
	{ WM_MBUTTONDOWN, CallbackID::on_mouse_mbtn_down },
	{ WM_RBUTTONDOWN, CallbackID::on_mouse_rbtn_down },
	{ WM_LBUTTONUP, CallbackID::on_mouse_lbtn_up },
	{ WM_MBUTTONUP, CallbackID::on_mouse_mbtn_up },
	{ WM_RBUTTONUP, CallbackID::on_mouse_rbtn_up },
	{ WM_LBUTTONDBLCLK, CallbackID::on_mouse_lbtn_dblclk },
	{ WM_MBUTTONDBLCLK, CallbackID::on_mouse_mbtn_dblclk },
	{ WM_RBUTTONDBLCLK, CallbackID::on_mouse_rbtn_dblclk },
	{ WM_MOUSEMOVE, CallbackID::on_mouse_move },
	{ WM_MOUSEWHEEL, CallbackID::on_mouse_wheel },
	{ WM_MOUSEHWHEEL, CallbackID::on_mouse_wheel_h },
	{ WM_SYSKEYDOWN, CallbackID::on_key_down },
	{ WM_KEYDOWN, CallbackID::on_key_down },
	{ WM_KEYUP, CallbackID::on_key_up },
	{ WM_CHAR, CallbackID::on_char },
};
