name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Set repo variable
      run: |
        $repo = "${{ github.repository }}".Split("/")[1]
        echo "REPO=$repo" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Apply Scintilla Patch
      run: git apply scintilla-jsp/patches/jsp.patch

    - name: Build
      run: msbuild /m '/p:Platform=Win32;Configuration=${{ matrix.configuration }}' src\${{ env.REPO }}.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: startsWith(github.ref, 'refs/tags')
      with:
        name: ${{ env.REPO }}-${{ github.ref_name }}-${{ matrix.configuration }}
        path: component/
